# Site settings
# Enter your own credentials here
title: "My Blog"
email: you@somewhere.com
description: >
  Tell us about your site
baseurl: "/MIC-Packed-Particles" # replace ``/research-pages`` with the name of the parents repository
url: "Mahdi-Roozbahani.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
twitter_username: twitterhandle
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5


gh:
  user: Mahdi-Roozbahani
  repo: MIC-Packed-Particles
  # Branch hosting Github pages
  branch: gh-pages
